//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SCADA911
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Digital
	{
		public virtual string Name
		{
			get;
			set;
		}

		public virtual string ItemName
		{
			get;
			set;
		}

		public virtual string Description
		{
			get;
			set;
		}

		public virtual string State0
		{
			get;
			set;
		}

		public virtual string State1
		{
			get;
			set;
		}

		public virtual Group Group
		{
			get;
			set;
		}

	}
}

