//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SCADA911
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Group
	{
		public virtual string Name
		{
			get;
			set;
		}

		public virtual User User
		{
			get;
			set;
		}

		public virtual Digital DAlarm
		{
			get;
			set;
		}

	}
}

