//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SCADA911
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Sound
	{
		public virtual string Path
		{
			get;
			set;
		}

		public virtual string Name
		{
			get;
			set;
		}

		public virtual void PlaySound(string SoundName)
		{
			throw new System.NotImplementedException();
		}

	}
}

