//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SCADA911
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class User
	{
		public virtual string Name
		{
			get;
			set;
		}

		public virtual string Phone2
		{
			get;
			set;
		}

		public virtual string Email
		{
			get;
			set;
		}

		public virtual string SMSPhone
		{
			get;
			set;
		}

		public virtual int Code
		{
			get;
			set;
		}

		public virtual string Sound
		{
			get;
			set;
		}

		public virtual string Phone1
		{
			get;
			set;
		}

	}
}

